version: "3.9"

services:
  backend:
    image: sunguk1995/su-interactive-self-interview-backend:latest
    container_name: su-backend
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    image: sunguk1995/su-interactive-self-interview-frontend:latest
    container_name: su-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"          # ğŸ‘‰ ì™¸ë¶€ì—ì„œ ì ‘ê·¼ì‹œ í”„ë¡ íŠ¸ëŠ” 80 í¬íŠ¸ë¡œ ì—´ë¦¼
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://backend:8000  # âœ… Docker ë‚´ë¶€ í†µì‹ 
    restart: always
